---

- name: APT Update
  hosts: all
  tasks:
    - name: General Update
      ansible.builtin.apt:
        upgrade: full
      become: true

    - name: Update PiHole
      ansible.builtin.command: pihole -up
      when: pihole
      register: phout
      changed_when: 'update available' in phout.stdout

    - name: debug
      debug:
        var: phout
